// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATpw88pswTeroV6TAL_6JGym0JL7JY0GU',
    appId: '1:502205965007:web:4ac90c8a65d30d0c4e4dba',
    messagingSenderId: '502205965007',
    projectId: 'projectapp-19f39',
    authDomain: 'projectapp-19f39.firebaseapp.com',
    storageBucket: 'projectapp-19f39.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt2tgrK7mQ4xCX08YqG5aF9LYaZccg0x4',
    appId: '1:502205965007:android:1184e58218e202cd4e4dba',
    messagingSenderId: '502205965007',
    projectId: 'projectapp-19f39',
    storageBucket: 'projectapp-19f39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO7J_Vqk32Jy5NZHHDL4KRDQcVC2Wh61I',
    appId: '1:502205965007:ios:1c2e8fb3168ecab14e4dba',
    messagingSenderId: '502205965007',
    projectId: 'projectapp-19f39',
    storageBucket: 'projectapp-19f39.appspot.com',
    iosClientId: '502205965007-41q53gam33254tuaum7vodo3egf9crbc.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO7J_Vqk32Jy5NZHHDL4KRDQcVC2Wh61I',
    appId: '1:502205965007:ios:1a329515afe7c4504e4dba',
    messagingSenderId: '502205965007',
    projectId: 'projectapp-19f39',
    storageBucket: 'projectapp-19f39.appspot.com',
    iosClientId: '502205965007-a28b2shln9ufksl5cruuve84dg2ij3qt.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectapp.RunnerTests',
  );
}
